# Autogenerated wrapper script for rubberband_jll for x86_64-apple-darwin
export librubberband, rubberband

using FFTW_jll
using libsamplerate_jll
using libsndfile_jll
JLLWrappers.@generate_wrapper_header("rubberband")
JLLWrappers.@declare_library_product(librubberband, "@rpath/librubberband.dylib")
JLLWrappers.@declare_executable_product(rubberband)
function __init__()
    JLLWrappers.@generate_init_header(FFTW_jll, libsamplerate_jll, libsndfile_jll)
    JLLWrappers.@init_library_product(
        librubberband,
        "lib/librubberband.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        rubberband,
        "bin/rubberband",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
